# Generated by Django 2.2 on 2020-10-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='название')),
                ('description', models.TextField(verbose_name='содержание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='дата редактирования')),
                ('status', models.BooleanField(default=True, verbose_name='активен')),
                ('descriptor', models.CharField(max_length=30, null=True, verbose_name='тэги')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='Телефон')),
                ('town', models.CharField(max_length=1500, null=True, verbose_name='Город')),
                ('check', models.BooleanField(default=True, verbose_name='Верифицирован')),
                ('count_news', models.IntegerField(null=True, verbose_name='Опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник')),
                ('text', models.TextField(verbose_name='текст комментария')),
                ('news', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.News', verbose_name='новость')),
                ('user', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
