# Generated by Django 2.2 on 2020-10-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptor',
        ),
    ]
