# Generated by Django 2.2 on 2020-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_news_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='descriptor',
            field=models.CharField(max_length=30, null=True, verbose_name='тэги'),
        ),
    ]
