# Generated by Django 2.2 on 2020-10-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_news_descriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptor',
        ),
        migrations.CreateModel(
            name='Metatags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=15, null=True, verbose_name='тэги')),
                ('news', models.ManyToManyField(default=None, null=True, to='app_users.News')),
            ],
        ),
    ]
