# Generated by Django 2.2 on 2020-10-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20201006_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nick',
        ),
    ]
