# Generated by Django 2.2 on 2020-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_news_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=False, verbose_name='активен'),
        ),
    ]
