# Generated by Django 2.2 on 2020-10-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20201015_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatags',
            name='news',
        ),
        migrations.AddField(
            model_name='news',
            name='descriptor',
            field=models.ManyToManyField(blank=True, max_length=15, null=True, to='app_users.Metatags', verbose_name='тэги'),
        ),
    ]
