# Generated by Django 2.2 on 2020-10-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_auto_20201015_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='descriptor',
            field=models.CharField(default=1, max_length=21, verbose_name='тэги'),
            preserve_default=False,
        ),
    ]
