# Generated by Django 2.2 on 2020-10-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0012_auto_20201015_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptor',
        ),
        migrations.AddField(
            model_name='news',
            name='descriptor',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_users.Metatags', verbose_name='тэги'),
        ),
    ]
