# Generated by Django 2.2 on 2020-10-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_auto_20201015_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='descriptor',
        ),
        migrations.AddField(
            model_name='news',
            name='metatags',
            field=models.CharField(blank=True, max_length=21, verbose_name='теги'),
        ),
        migrations.DeleteModel(
            name='Metatags',
        ),
    ]
