# Generated by Django 2.2 on 2020-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20201016_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='metatags',
        ),
        migrations.AddField(
            model_name='news',
            name='metatags',
            field=models.CharField(blank=True, max_length=21),
        ),
        migrations.DeleteModel(
            name='Metatags',
        ),
    ]
