# Generated by Django 2.2 on 2020-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_auto_20201016_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metatag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(blank=True, max_length=21, null=True, verbose_name='тэги')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='metatags',
        ),
        migrations.AddField(
            model_name='news',
            name='metatag',
            field=models.ManyToManyField(blank=True, max_length=21, null=True, to='app_users.Metatag'),
        ),
    ]
