# Generated by Django 2.2 on 2020-10-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_auto_20201028_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatag',
            options={'verbose_name_plural': 'Metatag'},
        ),
    ]
