# Generated by Django 2.2 on 2020-10-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_auto_20201028_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatag',
            options={},
        ),
    ]
