# Generated by Django 2.2 on 2020-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0021_auto_20201031_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='image'),
        ),
    ]
