# Generated by Django 2.2 on 2020-11-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0023_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
