# Generated by Django 2.2 on 2020-11-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0027_auto_20201111_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_pictures_news', to='app_users.News'),
        ),
    ]
