# Generated by Django 2.2 on 2020-12-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0028_auto_20201113_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='metatag',
        ),
        migrations.DeleteModel(
            name='Metatag',
        ),
    ]
